In [1]:
import numpy as np

In [2]:
#single-dimensional numpy array
n1 = np.array([10,20,30,40,50])
n1

array([10, 20, 30, 40, 50])

In [3]:
type(n1)

numpy.ndarray

In [4]:
#multi-dimensional numpy array
n2 = np.array([[10,20,30],[30,20,10]])
n2

array([[10, 20, 30],
       [30, 20, 10]])

In [5]:
type(n2)

numpy.ndarray

In [6]:
#initializing numpy array with zeros
n1 = np.zeros((1,2))
n1

array([[0., 0.]])

In [7]:
n2 = np.zeros((3,3))
n2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
n3 = np.full((2,3),6)
n3

array([[6, 6, 6],
       [6, 6, 6]])

In [9]:
#range (2nd value is exclusive)
n1 = np.arange(2,10)
n1

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
n2 = np.arange(20,70,5)
n2

array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

In [12]:
#3 numbers between 1-20
d320 = np.random.randint(1,20,3)
d320

array([18, 13,  5])

In [14]:
n1 = np.array([[1,2,3],[4,5,6]])
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
n1.shape

(2, 3)

In [16]:
n1.shape = (3,2)

In [17]:
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
n1 = np.array([10,20])
n2 = np.array([30,40])
np.sum([n1,n2])

100

In [19]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [20]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [21]:
#vstack hstack column_stack
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [22]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [23]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])